/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMerchantIndexRouteImport } from './routes/_authenticated/merchant.index'
import { Route as AuthenticatedCourierIndexRouteImport } from './routes/_authenticated/courier.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin.users'
import { Route as AuthenticatedMerchantNewRouteImport } from './routes/_authenticated/merchant.new'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMerchantIndexRoute =
  AuthenticatedMerchantIndexRouteImport.update({
    id: '/merchant/',
    path: '/merchant/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCourierIndexRoute =
  AuthenticatedCourierIndexRouteImport.update({
    id: '/courier/',
    path: '/courier/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMerchantNewRoute =
  AuthenticatedMerchantNewRouteImport.update({
    id: '/merchant/new',
    path: '/merchant/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/admin/orders',
    path: '/admin/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/merchant/new': typeof AuthenticatedMerchantNewRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/courier/': typeof AuthenticatedCourierIndexRoute
  '/merchant/': typeof AuthenticatedMerchantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/merchant/new': typeof AuthenticatedMerchantNewRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/courier': typeof AuthenticatedCourierIndexRoute
  '/merchant': typeof AuthenticatedMerchantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/merchant/new': typeof AuthenticatedMerchantNewRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/courier/': typeof AuthenticatedCourierIndexRoute
  '/_authenticated/merchant/': typeof AuthenticatedMerchantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/orders'
    | '/admin/users'
    | '/merchant/new'
    | '/api/admin/users'
    | '/admin/'
    | '/courier/'
    | '/merchant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/orders'
    | '/admin/users'
    | '/merchant/new'
    | '/api/admin/users'
    | '/admin'
    | '/courier'
    | '/merchant'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/users'
    | '/_authenticated/merchant/new'
    | '/api/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/courier/'
    | '/_authenticated/merchant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/merchant/': {
      id: '/_authenticated/merchant/'
      path: '/merchant'
      fullPath: '/merchant/'
      preLoaderRoute: typeof AuthenticatedMerchantIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courier/': {
      id: '/_authenticated/courier/'
      path: '/courier'
      fullPath: '/courier/'
      preLoaderRoute: typeof AuthenticatedCourierIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/merchant/new': {
      id: '/_authenticated/merchant/new'
      path: '/merchant/new'
      fullPath: '/merchant/new'
      preLoaderRoute: typeof AuthenticatedMerchantNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedMerchantNewRoute: typeof AuthenticatedMerchantNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCourierIndexRoute: typeof AuthenticatedCourierIndexRoute
  AuthenticatedMerchantIndexRoute: typeof AuthenticatedMerchantIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedMerchantNewRoute: AuthenticatedMerchantNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCourierIndexRoute: AuthenticatedCourierIndexRoute,
  AuthenticatedMerchantIndexRoute: AuthenticatedMerchantIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
